version: '2'
services:
    angularspringapp1-app:
        image: angularspringapp1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angularspringapp1-mysql:3306/angularspringapp1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angularspringapp1-mysql:
        extends:
            file: mysql.yml
            service: angularspringapp1-mysql
